- name: Show running config
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Get running config
      ios_command:
        commands: show running-config
      register: showrun_output

    - name: Save running config to local file
      local_action:
        module: copy
        content: "{{ showrun_output.stdout[0] }}"
        dest: "{{ output_file }}"